### ISSUE TITLE
StreamingAnnotateVideo RPC failed: Code(12): GRPC target method can't be resolved.

### ISSUE THREAD

**Issue by AdityaGovardhan** [google/aistreamer#2]
I am trying to stream my webcam output to video intelligence API (which I am aware is in beta version). I am running a docker file provided in [env](https://github.com/google/aistreamer/tree/master/ingestion/env) folder. As described in the [example](https://github.com/google/aistreamer/blob/master/ingestion/documentation/live.md), I was able to start aistreamer using following command:

`./streaming_client_main --alsologtostderr --endpoint "dns:///videointelligence.googleapis.com"       --video_path=$PIPE_NAME --use_pipe=true --config=$CONFIG --timeout=$TIMEOUT`

To feed the pipe with gstreamer pipeline output I used following gstreamer command:

`gst-launch-1.0 v4l2src device=/dev/video0 ! videoconvert ! video/x-raw,format=I420,width=640,height=480,framerate=30/1 ! x264enc  bframes=0 key-int-max=45 bitrate=500 ! video/x-h264,stream-format=avc,alignment=au,profile=baseline ! filesink location=$PIPE_NAME`

However, there is no response, the output is stuck at:
`WARNING: Logging before InitGoogleLogging() is written to STDERR
`
`
I0426 01:34:56.147866  6301 streaming_client.cc:132] Received 0 responses.
`

And when I close the gstreamer pipeline, I get the following output:
`
I0426 01:35:15.143780  6302 pipe_reader.cc:116] Pipe /google/cpp/streaming-pipe has been closed by remote side.
`
`
I0426 01:35:15.144083  6297 streaming_client.cc:205] Sent 305 requests consisting of 592599 bytes of video data in total.
`
`
E0426 01:35:15.144237  6297 streaming_client.cc:103] StreamingAnnotateVideo RPC failed: Code(12): GRPC target method can't be resolved.
`

After going through gRPC docs I think I am using wrong name for video intelligence API but I don't know what name to use since the streaming part is in beta version.

**Comment by eecoolboy** [comment]
Hi Aditya,

Sorry for the late response. For some reasons, I was not notified by this discussion. 
We have an updated release in May. Could you please have a try?

Also to better debugging your gst command line, could you please save your camera feed into
a local file, and make sure it is playable by ffplay? After verification, try the video file with either C++ or Python client sample code. If it works, that means your gst command line is good, and you can then try live. For other questions, please feel free to directly send me an email at zixia@google.com.  Thanks!
code

**Comment by AdityaGovardhan** [comment]
Hi @eecoolboy ,

The sample is working for me now, thank you.
