### ISSUE TITLE
The `ppa:jonathonf/ffmpeg-3`, not found

### ISSUE THREAD

**Issue by manoelsmotoso** [google/aistreamer#6]
Docker image doesn't build.
Error:
`Step 6/37 : RUN add-apt-repository ppa:jonathonf/ffmpeg-3 -y
 ---> Running in 5047ea9a7292
Cannot add PPA: 'ppa:~jonathonf/ubuntu/ffmpeg-3'.
The user named '~jonathonf' has no PPA named 'ubuntu/ffmpeg-3'
`

I changed to `RUN add-apt-repository ppa:jonathonf/ffmpeg-4 -y`, and works.

**Comment by joshuapinter** [comment]
Correct. `jonathonf/ffmpeg-3` no longer exists and needs to now be `jonathonf/ffmpeg-4`.

Additionally, if you already had `jonathonf/ffmpeg-3` setup as a PPA then you need to remove that by deleting it from `/etc/apt/sources.list.d/` and then adding `jonathonf/ffmpeg-4` with `add-apt-repository ppa:jonathonf/ffmpeg-4`.
